### ISSUE TITLE
ArgumentError: min out of range

### ISSUE THREAD

**Issue by MSeneadza** [simplymadeapps/simple_scheduler#13]
Have you seen this error before?

```
ArgumentError: min out of range
- 92 non-project frames
1
File "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb" line 111 in utc
2
File "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb" line 111 in change
3
File "/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/time_with_zone.rb" line 462 in method_missing
4
File "/app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.5/lib/simple_scheduler/at.rb" line 98 in parsed_time
5
File "/app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.5/lib/simple_scheduler/at.rb" line 28 in initialize
6
File "/app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.5/lib/simple_scheduler/task.rb" line 31 in new
7
File "/app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.5/lib/simple_scheduler/task.rb" line 31 in at
```

I started getting it just after adding and deploying the last job below:

```
queue_ahead: 360 # Number of minutes to queue jobs into the future
tz: "America/New_York" # The application time zone will be used by default if not set

update_prices_otcbb:
  class: "UpdatePricesOtcbbWorker"
  every: "1.day"
  at: "18:10"
  expires_after: "2.hours"
  tz: "America/New_York"

post_update_prices_otcbb:
  class: "PostUpdatePricesOtcbbWorker"
  every: "1.day"
  at: "18:50"
  expires_after: "2.hours"
  tz: "America/New_York"

company_profiles_otcbb:
  class: "CompanyProfileOtcbbWorker"
  every: "1.hour"
  at: "*:45"

company_profiles_canada:
  class: "CompanyProfileCanadaWorker"
  every: "1.hour"
  at: "*:15"
```

The first three jobs had been there for a few hours and working fine.  

I tried debugging it by changing `*:15` to other times bit that didn't fix it.  Then I got to the point where I just commented out the last job but I still got the exception.  Then I commented out both of the last 2 jobs but the exception was still being thrown. 

At this point I started to suspect that something weird was going on because of the time of day.  I happened to push the new job for the first time just after 11pm Eastern time. (My server is UTC but timezone in the config is set to `America/New_York`) When I started thinking this it was just a couple of minutes before midnight.  Low and behold, after midnight things are working fine with all four jobs' configs uncommented. 

I'll keep an eye on how things go tomorrow night to see if it was actually something to do with the time of day.

**Comment by brianpattison** [comment]
Thanks for the detailed description. Do you know if the error occurred when the rake task was performed to parse the config and add the scheduled jobs? Or did the rake task succeed and the error occurred when the FutureJob was executed by Sidekiq? Those are the two places that the time is parsed by `SimpleScheduler::At`. 

Looking at my regex for parsing the `at` time, I can improve it slightly. It looks like I'm accepting invalid times like "99:99" so I shouldn't do that. But I don't think that's the problem. I'm not sure how to replicate this, but I can help you debug it further.

See if this will give you the same error message in your Rails console to make sure I'm understanding the error correctly:

```ruby
# Time can't be 99 minutes. I assume that's what "min out of range" is telling us
SimpleScheduler::At.new("*:99", ActiveSupport::TimeZone.new("America/New_York"))
```

So if you do run into this error again, try this in your Rails console:

```ruby
# Does it cause the error because of something not handled with the time of day?
SimpleScheduler::At.new("*:15", ActiveSupport::TimeZone.new("America/New_York"))
```

The only other thing to test is the regex for matching the time, but I can tell you that the same results will come back no matter what time of day, so I don't think that would help.

```ruby
AT_PATTERN = /(Sun|Mon|Tue|Wed|Thu|Fri|Sat)?\s?(?:\*{1,2}|(\d{1,2})):(\d{1,2})/
match = AT_PATTERN.match("*:15")
match[3]
# => "15"
```

Finally, if you want to dive really deep, you could fork the repo and add some logging around here:

<https://github.com/simplymadeapps/simple_scheduler/blob/master/lib/simple_scheduler/at.rb#L98>

Log the `@parsed_time`, the `change_hour`, and the `at_min`. What's getting passed into the change that's causing the time to be out of range?

I hope we can replicate this and fix it!

**Comment by MSeneadza** [comment]
Thanks for the debugging tips.  I may give it a crack this weekend.  So it certainly seems that it's an issue with the last hour of the day.  I just checked my logs and I see some more between 11 & midnight on Friday.  I made one change to the config file at 6:45pm on Friday. It was scheduling fine the entire day until 
![screenshot 2017-03-17 23 59 45](https://cloud.githubusercontent.com/assets/1416050/24068789/19bf8b70-0b6e-11e7-9481-cee5d7715e30.png)

Note that it's interesting that the 11:03 & 11:13 runs seemed to go fine.

**Comment by MSeneadza** [comment]
I see you updated the gem.  I just deployed the new version.  We'll see what happens Saturday night...

**Comment by brianpattison** [comment]
Thanks for the update. So interesting... we have never seen this error and we have jobs that run every 10 minutes, starting at the top of the hour. The new gem version will do a better job of letting you know that the `at` time is invalid, but I'll be surprised if you get the new error.

I'll try to do some time traveling in the test suite to see if I can replicate this, but if you have a chance to debug on your server during the 11 o'clock hour, that could help a ton since I won't be able to replicate your entire environment.

Thanks for helping out to track this down! Let me know if there's anything else I can do to help.

**Comment by MSeneadza** [comment]
So I haven't had a chance to do any debugging yet but the same errors occurred last night, with 0.2.6.  I didn't see the new, nicer exceptions in my RollBar...
![screenshot 2017-03-19 09 23 53](https://cloud.githubusercontent.com/assets/1416050/24081230/148aa6bc-0c86-11e7-8e4b-2fe3db15887f.png)

**Comment by MSeneadza** [comment]
OK, I think I figured it out.  So let's say it's after 11 pm and you pass an `at_min` with a wildcard `at_hour`.  If `at_min` is less than the current time's minute  (e.g. the current time is 23:32 and we've passed `*:30`) the 'min out of range' exception is thrown.  But I think it's really the hour that's bad.  In that situation the gem passes an hour of 24 in `parsed_day.change(hour: change_hour, min: at_min)`

Here's what I just did in my console:
```
irb(main):008:0> SimpleScheduler::At.new("*:15", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb:111:in `utc'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb:111:in `change'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/time_with_zone.rb:462:in `method_missing'
	from /app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.6/lib/simple_scheduler/at.rb:105:in `parsed_time'
	from /app/vendor/bundle/ruby/2.4.0/gems/simple_scheduler-0.2.6/lib/simple_scheduler/at.rb:31:in `initialize'
	from (irb):8:in `new'
	from (irb):8
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):009:0> Time.current
=> Mon, 20 Mar 2017 03:51:06 UTC +00:00
# 23:51 in "America/New_York"

=> Mon, 20 Mar 2017 03:51:06 UTC +00:00
irb(main):010:0> SimpleScheduler::At.new("*:05", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range

irb(main):011:0> SimpleScheduler::At.new("*:25", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range

irb(main):012:0> SimpleScheduler::At.new("*:35", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range

irb(main):013:0> SimpleScheduler::At.new("*:45", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range

irb(main):014:0> SimpleScheduler::At.new("*:55", ActiveSupport::TimeZone.new("America/New_York"))
=> 2017-03-19 23:55:00 -0400
irb(main):015:0> Time.current
=> Mon, 20 Mar 2017 03:52:44 UTC +00:00
irb(main):016:0> SimpleScheduler::At.new("*:53", ActiveSupport::TimeZone.new("America/New_York"))
=> 2017-03-19 23:53:00 -0400

irb(main):022:0> Time.current
=> Mon, 20 Mar 2017 03:54:00 UTC +00:00
irb(main):023:0> SimpleScheduler::At.new("*:53", ActiveSupport::TimeZone.new("America/New_York"))
ArgumentError: min out of range

irb(main):024:0> Time.current
=> Mon, 20 Mar 2017 03:54:22 UTC +00:00
irb(main):025:0> SimpleScheduler::At.new("*:54", ActiveSupport::TimeZone.new("America/New_York"))
=> 2017-03-19 23:54:00 -0400
irb(main):026:0> SimpleScheduler::At.new("*:55", ActiveSupport::TimeZone.new("America/New_York"))
=> 2017-03-19 23:55:00 -0400

# **** it worked because 54 & 55 are >= the current minute's 54
```
Below I'm essentially walking through the flow of `at.rb` to set up variables to execute line 105:
```
irb(main):028:0> zone = ActiveSupport::TimeZone['America/New_York']
=> #<ActiveSupport::TimeZone:0x0000000211a740 @name="America/New_York", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: America/New_York>>
irb(main):029:0> time_locally = Time.now
=> 2017-03-20 03:58:14 +0000
irb(main):030:0> time_in_zone = zone.at(time_locally)
=> Sun, 19 Mar 2017 23:58:14 EDT -04:00
irb(main):031:0> now = _
=> Sun, 19 Mar 2017 23:58:14 EDT -04:00
irb(main):032:0> parsed_day = now.beginning_of_day
=> Sun, 19 Mar 2017 00:00:00 EDT -04:00
irb(main):033:0> now.min
=> 58
irb(main):034:0> 15 < now.min
=> true
irb(main):035:0> 59 < now.min
=> false
irb(main):036:0> now.hour.to_i
=> 23
irb(main):037:0> AT_PATTERN = /(Sun|Mon|Tue|Wed|Thu|Fri|Sat)?\s?(?:\*{1,2}|((?:\b[0-1]?[0-9]|2[0-3]))):([0-5]\d)/
=> /(Sun|Mon|Tue|Wed|Thu|Fri|Sat)?\s?(?:\*{1,2}|((?:\b[0-1]?[0-9]|2[0-3]))):([0-5]\d)/
irb(main):038:0> AT_PATTERN.match('*:15')
=> #<MatchData "*:15" 1:nil 2:nil 3:"15">
irb(main):039:0> at_hour = now.hour.to_i
=> 23
irb(main):040:0> change_hour = at_hour
=> 23
irb(main):041:0> hour = false
=> false
irb(main):046:0> at_min = 15
=> 15
irb(main):047:0> next_hour = !hour && at_min < now.min
=> true
# next line is from at.rb line 104
irb(main):048:0> change_hour += 1
=> 24

irb(main):050:0> parsed_day
=> Sun, 19 Mar 2017 00:00:00 EDT -04:00
irb(main):051:0> parsed_day.change(hour: change_hour, min: at_min)
ArgumentError: min out of range
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb:111:in `utc'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/core_ext/time/calculations.rb:111:in `change'
	from /app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/time_with_zone.rb:462:in `method_missing'
	from (irb):51
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/console.rb:65:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/console_helper.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
irb(main):052:0> parsed_day.change(hour: 0, min: at_min)
=> Sun, 19 Mar 2017 00:15:00 EDT -04:00
```

So I think the fix is to add a day to `@parsed_time` if it's between 11pm & midnight and the passed `at_min` is greater than the current time's minute and if there was no `at_hour` passed. Or something like that :-)

**Comment by brianpattison** [comment]
Ok, this is starting to make sense now. Thanks for the investigation work! I'll try to get this patched early this week. I'm thinking we haven't run into this bug because we schedule our 10 minute tasks at the top of the hour.

**Comment by MSeneadza** [comment]
Glad I could help!  Thanks again for the gem.  It's really a big help to me.

**Comment by brianpattison** [comment]
@MSeneadza Thanks again! Just reopen this issue if the new gem version doesn't solve your problem, but the test I added failed with your error and now it passes with the expected time:

<https://github.com/simplymadeapps/simple_scheduler/pull/16/files#diff-e3d807f428efba6e2bead7c974afbf8eR125>
