### ISSUE TITLE
Features need for 1.0

### ISSUE THREAD

**Issue by ACPK** [simplymadeapps/simple_scheduler#18]
@simplymadeapps I noticed that the version is currently set at 0.2.7.

If my team may ask, what features would be needed (in your opinion) for the gem to be ready for production? We're happy to help if applicable!

**Comment by bmedenwald** [comment]
Good news, we're using this in production for [Simple In/Out](https://www.simpleinout.com) right now and have been since December. The version number came out of our initial usage, but we believe it's quite solid and bet our business on it every day.

**Comment by ACPK** [comment]
@bmedenwald - Awesome, thanks!
