### ISSUE TITLE
Monthly job

### ISSUE THREAD

**Issue by danielmcoelho** [simplymadeapps/simple_scheduler#20]
Hi! 
I can't seem to find the monthly "at" options. I want to run a Job each first day of the month, not "in one month". Can I do this with the current version of `simple_scheduler`?

**Comment by bmedenwald** [comment]
As you suggest, you can perform jobs every month.  However, Simple Scheduler doesn't have an `at` condition that allows you to choose a calendar day of the month.

That's not a bad idea for a future feature.

For now, you can work around this issue by added a job to run every day. In that job, you can check the `scheduled_time` Simple Scheduler passes in and if it's not the first of the month you can simply return. This way the job only runs on the first of the month.
