### ISSUE TITLE
Time Zone - scheduled_time

### ISSUE THREAD

**Issue by ACPK** [simplymadeapps/simple_scheduler#21]
What time zone will scheduled_time be in?

**Comment by brianpattison** [comment]
The time passed into your job will be the epoch time as an integer, so UTC.

<https://github.com/simplymadeapps/simple_scheduler#writing-your-jobs>

You can easily parse it in any time zone:

```ruby
Time.use_zone("America/New_York") do
  puts Time.zone.at(scheduled_time)
end
```
