### ISSUE TITLE
Getting "ArgumentError: wrong number of arguments (given 0, expected 1..2)"...

### ISSUE THREAD

**Issue by MSeneadza** [simplymadeapps/simple_scheduler#24]
After I modified some of my jobs to accept one more (optional) parameter in the perform method I started getting:

```
ArgumentError: wrong number of arguments (given 0, expected 1..2)
1
File "/app/app/workers/update_prices_otcbb_worker.rb" line 6 in perform
```

So my perform definition looks like: `def perform(scheduled_time, my_param=nil)`

I'm not expecting simple_scheduler to pass `my_param`, rather, my intention for adding that param is that I may need to manually run that worker, passing it the date which needs to be processed.  So, in effect, I just want simple_scheduler to ignore it and keep working as it was when `perform` was only expecting `scheduled_time` to be passed.  

I think I've found the bug.  It's in the usage of `arity` in `FutureJob#queue_task`.  That has:

```  
    if @task.job_class.instance_method(:perform).arity > 0
        @task.job_class.send(perform_method, @scheduled_time.to_i)
      else
        @task.job_class.send(perform_method)
      end
```

However, `arity` returns a negative number for methods that have a variable number of arguments - https://ruby-doc.org/core-2.2.0/Method.html#method-i-arity

**Comment by brianpattison** [comment]
Ah, yes. I didn't realize that arity returns -1 in that case! Good timing on this because we're actually knocking out all the issues today and pushing out a release. I'll be sure to include the easy fix for this.

**Comment by brianpattison** [comment]
@MSeneadza [v0.3.0](https://github.com/simplymadeapps/simple_scheduler/releases/tag/v0.3.0) is out! 😁

**Comment by MSeneadza** [comment]
Sweet.  You guys are quick!  Thanks again.  This gem is really working out well for me.  I was so tired of dealing with Heroku Scheduler.
