### ISSUE TITLE
Interval configurations in simple_scheduler.yml was not followed. 

### ISSUE THREAD

**Issue by ChunAllen** [simplymadeapps/simple_scheduler#30]
Hi I'm following the instruction on the Read Me and I'm using Sidekiq and Heroku. 

I have this configuration on my **config/scheduler.yml**
```
tz: "Asia/Singapore"

notification_worker_job:
  class: 'SendNotificationWorker'
  every: '2.minutes'
```
and on my **Heroku Scheduler**:
<img width="864" alt="screenshot 2017-05-29 18 09 29" src="https://cloud.githubusercontent.com/assets/2100728/26545903/faf00598-4499-11e7-9102-2addefef13d4.png">

I'm expecting to run the job ** every 2 minutes** because I set it on the scheduler.yml file 
but the worker only runs **every 10 minutes** which is set on Heroku Scheduler. 

My question is why is it not following the **every 2 minutes** set on scheduler.yml file.

**Comment by brianpattison** [comment]
@ChunAllen You need to change your Heroku Scheduler command to be `rake simple_scheduler` without the ":reset"

**Comment by ChunAllen** [comment]
Hi @brianpattison thanks for answering but it's still not working 
<img width="803" alt="screenshot 2017-05-30 12 17 15" src="https://cloud.githubusercontent.com/assets/2100728/26567931/f1cbdfb2-4531-11e7-86cb-1b3558fcc815.png">

It's still following the every 10mins set on Heroku Scheduler and not every 1 min set on simple_scheduler.yml
<img width="1680" alt="screenshot 2017-05-30 12 18 06" src="https://cloud.githubusercontent.com/assets/2100728/26567951/1ab3feb4-4532-11e7-8d74-2c473bab7086.png">

**Comment by brianpattison** [comment]
@ChunAllen 

I created a `simple_scheduler.yml` file with the following to try to debug your issue:

```yml
tz: "Asia/Singapore"

queue_reminder_notifications:
  class: 'ExampleJob'
  every: '2.minutes'
```

In my local development environment I ran `bundle exec rake simple_scheduler` and I ended up with over 180 items in Scheduled Jobs. This is what you should be seeing as well, so I'm not sure why you're not. I can see that there's 0 Scheduled Jobs in your Sidekiq UI.

![screen shot 2017-05-30 at 8 36 53 am](https://cloud.githubusercontent.com/assets/124570/26586662/7ab30e4e-4515-11e7-8342-82bf3812de01.png)

**Comment by ChunAllen** [comment]
I get it now. So every 10 minutes Heroku Scheduler will schedule a job that will run after 2 mins. 
I thought it will override the frequencies set on Heroku Scheduler.
