### ISSUE TITLE
Support for Sidekiq > 5.0? 

### ISSUE THREAD

**Issue by kaptron** [simplymadeapps/simple_scheduler#31]
Just tried installing this on a project using Sidekiq 5.0 and ran into a dependency issue because of the `~> 4.2` requirement for sidekiq in the gemspec. Is there anything holding this back from being 5.0 compatible? For now I'll just roll back to Sidekiq 4.2.10. Thanks!

**Comment by brianpattison** [comment]
@kaptron We haven't looked into compatibility with Sidekiq 5.0 yet, but I should have a chance to look into it tomorrow! As long as it all works, we'll add 5.0 support to the gem spec. Thanks for pointing it out!

**Comment by carlo** [comment]
Thank you, @brianpattison! Much obliged.
