### ISSUE TITLE
How to test in a development environment?

### ISSUE THREAD

**Issue by abebraham** [simplymadeapps/simple_scheduler#36]
I have spent the last 2 months learning rails so please excuse if this question is misplaced. 

I want to test if my application can send an email every 2 minutes (just for testing, not going to be in the final product). I have gotten Sidekiq working, but I am struggling to figure out to send concurrent emails. 

From my understanding, the simple_scheduler only works in a deployed environment with Heroku right (not trying to talk this down, I plan on using this once I ready for deploying)?

Thanks
- Abraham

**Comment by volkerholloh** [comment]
You can use simple_scheduler in development, too. You only need a local redis server running. I got mine on mac os with homebrew.

Then you can write and run your jobs' tests.

Cheers,
Volker

**Comment by abebraham** [comment]
Oh, I see... Now correct me if I am wrong.  

Is this the correct output for the redis server?
```
$ redis-server
19738:C 02 Sep 21:19:44.982 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
19738:C 02 Sep 21:19:44.982 # Redis version=4.0.1, bits=64, commit=00000000, modified=0, pid=19738, just started
19738:C 02 Sep 21:19:44.982 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
19738:M 02 Sep 21:19:44.984 * Increased maximum number of open files to 10032 (it was originally set to 256).
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 4.0.1 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 19738
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

19738:M 02 Sep 21:19:44.985 # Server initialized
19738:M 02 Sep 21:19:44.985 * DB loaded from disk: 0.000 seconds
19738:M 02 Sep 21:19:44.985 * Ready to accept connections
19738:M 02 Sep 21:24:45.048 * 100 changes in 300 seconds. Saving...
19738:M 02 Sep 21:24:45.049 * Background saving started by pid 20468
20468:C 02 Sep 21:24:45.058 * DB saved on disk
19738:M 02 Sep 21:24:45.150 * Background saving terminated with success


```

Currently that is all that shows up on my redis-server. 

Thanks in advanced!

**Comment by abebraham** [comment]
Concept Questions

Q1: In order to test the following in development; I have to run "rake simple_scheduler" in my terminal more frequently than every 2 minutes correct? 

Q2: If so, then how does simple_scheduler work with Heroku, when Heroku calls the "rake simple_scheduler command every 10 minutes. 


_simple_scheduler.yml_
```
# Global configuration options. These can also be set on each task.
queue_ahead: 0        # Number of minutes to queue jobs into the future
tz: "America/Los_Angeles" # The application time zone will be used by default if not set

# Runs once every 2 minutes
simple_task:
  class: "SendEmailLaterJob"
  every: "2.minutes"
```

Again, I cannot thank you enough for taking the time to help me.

**Comment by volkerholloh** [comment]
Hi,

your output of the redis tab is exactly the same I have.

Your test environment:
If you only want to run you tests, you only need the following tabs in Terminal with the commands:
- bundle exec guard
- redis-server

If you want to run the whole thing in development, you need to run in tabs in Terminal:
- bundle exec sidekiq
- rails s

re Q1: It depends on your `queue_ahead`setting. Please see my answer to Q2. 360 minutes should get you through your development day. If not, simply fire `rake simple_scheduler` again. 

re Q2: It is important to set the queue_ahead to a much bigger value. The readme tells you why. Simple_scheduler recommends 360, that's minutes. So, with `rake simple_scheduler`, simple_scheduler produces a queue of jobs, depending on your `simple_scheduler.yml`, for the next 6 hours. Now, when you or Heroku `rake simple_scheduler` again, simple_scheduler appends the jobs of the time between the end of your existing queue and the `queue_ahead` time. So every 10 minutes your 360 minutes queue is filled.

Thank you for your questions, as it makes me to got through the stuff again, as I am a learner myself. :)

**Comment by abebraham** [comment]
Great thank you for your help! 👍 Really appreciate it.
