### ISSUE TITLE
Using shoryuken instead of sidekiq

### ISSUE THREAD

**Issue by oyeanuj** [simplymadeapps/simple_scheduler#49]
Hi @brianpattison! Thank you for creating this library - it looks great. I'd love to use it but I'm using shoryuken instead of sidekiq. 

I was wondering if this can be used with [shoryuken](https://github.com/phstc/shoryuken) instead of sidekiq? Are the specific tweaks or settings that might make it possible?

Thanks!

**Comment by oyeanuj** [comment]
FWIW, Shoryuken wiki says that they are a drop-in replacement for Sidekiq: https://github.com/phstc/shoryuken/wiki/From-Sidekiq-to-Shoryuken

**Comment by oyeanuj** [comment]
Ah, thank you for that context. I'm not super savvy with Shoryuken so I'll have to investigate more. 

Maybe @phstc, the author of Shoryuken might have more thoughts.

**Comment by phstc** [comment]
@oyeanuj there are some projects for Shoryuken, but I haven't used any. So I can't give further guidance. 

* https://github.com/joekhoobyar/shoryuken-later
* https://github.com/farski/shoryuken-waiter

But if you are using Heroku, can't you just call a rake task to enqueue a job every N minutes?

In AWS I would use CloudWatch events.

**Comment by brianpattison** [comment]
Feel free to reopen this issue if you have more questions. Thanks!
