### ISSUE TITLE
Question: Don't send scheduled_time

### ISSUE THREAD

**Issue by sqlninja** [simplymadeapps/simple_scheduler#51]
So I have a few workers that I use sidekiq-unique-jobs on.
In these jobs, they are fairly long-running, and I used the unique jobs gem to keep a second instance from starting if a previous instance is already going.

This works great until I schedule them because the unique jobs gem is using the params to check uniqueness and the since the timestamp is different on each run then it's considered unique.

I noticed that the scheduled_time is optional based on the [Writing your Jobs](https://github.com/simplymadeapps/simple_scheduler#writing-your-jobs) section, but when I just tried removing that param from the perform method, I started getting an argument error:
`ArgumentError: wrong number of arguments (given 1, expected 0)`

So my question here is, how do I not send the scheduled_time?

**Comment by sqlninja** [comment]
I'm posing a similar question to the sidekiq-unique-jobs as well on how to just ignore the params...

**Comment by sqlninja** [comment]
Worked it with the unique_args method in the sidekiq-unique-jobs gem...

**Comment by bmedenwald** [comment]
Good deal.

Simple Scheduler is built to avoid sending the `scheduled_time` if the `perform` method doesn't want to accept it. You can see that specific code [here](https://github.com/simplymadeapps/simple_scheduler/blob/4d186042507c1397ee79a5e8fe929cc14008c026/lib/simple_scheduler/future_job.rb#L82). 

While I'm not aware of the `sidekiq-unique-jobs` gem, I wonder if it's doing something as a super over the top of your job, thereby confusing the `arity` as to whether is should pass the parameter.

Glad you have a solution.

**Comment by sqlninja** [comment]
Well I also use `gem 'sidekiq-symbols'` which allow me to send optional params as a symbol, so some jobs params were only the scheduled_time and some have symbols..

For example:
```
def perform(scheduled_time)
   ...
end
```
vs
```
def perform(_scheduled_time, historical: false, debug: false)
...
end
```

So in case of arity, there were still params being sent to the perform method that was not scheduled_time...

Nonetheless, I solved in the unique-job method like this:
#This assumes the scheduled_time param is the first param...
```
def self.unique_args(args)
     #method from sidekiq-unique-jobs to override/control uniqueness
     ignore_scheduled_time?(args)
end

  def self.ignore_scheduled_time?(args)
    if args.present? && args.first.is_a?(Integer)
      #Remove the scheduled_time int from the args for uniqueness check
      args.shift
    end

    return args
  end
```
