### ISSUE TITLE
Scheduled Jobs Missing in Sidekiq

### ISSUE THREAD

**Issue by RaresSalcudean** [simplymadeapps/simple_scheduler#52]
Hello,

Recently I decided to use Simple Scheduler with Sidekiq for one of our newest projects. I did the setup, prepared the config files and deployed it to Heroku.

When viewing Sidekiq Web Interface with the latest version of Simple Scheduler (v. 1.0.0), in the Scheduled tab there are 0 jobs scheduled. 

<img width="1440" alt="Screenshot 2019-06-26 at 13 06 06" src="https://user-images.githubusercontent.com/29229646/60172245-f9400100-9814-11e9-83d3-694aab8561bd.png">

Is this by design?

In version v. 0.3.4, the scheduled jobs were visible in Sidekiq Web UI.

<img width="1233" alt="Screenshot 2019-06-26 at 13 32 52" src="https://user-images.githubusercontent.com/29229646/60173219-eaf2e480-9816-11e9-8c89-1d983b0bbe00.png">

Thank you!

**Comment by brianpattison** [comment]
Hi @RaresSalcudean,

There should definitely be Scheduled Jobs in your queue with all versions of Simple Scheduler. Hopefully I can help you debug what's going wrong. 

First of all, make sure you still have the Heroku Scheduler task set up to run `rake simple_scheduler` every 10 minutes.

The next step to debug the problem is to manually run `heroku run rake simple_scheduler` for your app. This should either plant the future jobs in the Scheduled Jobs queue or you should see it fail with an error.

Let me know how that goes and I can help you debug the problem further. Thanks!

**Comment by RaresSalcudean** [comment]
Hi @brianpattison,

I had to do a quick deploy today for a demo and used `sidekiq-cron`. The issue is that even in development the Scheduled Jobs do not show.

I was suspecting that you guys would suggest running `heroku run rake simple_scheduler` so I did a screenshot a couple of hours ago.

<img width="1440" alt="Screenshot 2019-06-26 at 13 15 50" src="https://user-images.githubusercontent.com/29229646/60186709-07057e80-9835-11e9-8f90-18820273ccf4.png">

It shows as the jobs are scheduled, but are not displayed in the Web UI.

Thank you!

**Comment by RaresSalcudean** [comment]
I believe the issue with Scheduled jobs is the fact I have a job that requires to be executed at a specific time only once a day. (This can be done by Heroku Scheduler by default)

Thus the `queue_ahead: 360` minutes won't display any Scheduled job in the future. 
```

queue_ahead: 360 # Number of minutes to queue jobs into the future
queue_name: "default"
tz: "Europe/Bucharest"

InactiveFlagStatus:
  class: "GolferClubsStatusWorker"
  every: "1.day"
  at: "14:00"
  expires_after: "23.hours"

```

The main issue was that the Job did not get executed around `14:00` and I could not figure out why not, I have almost the same setup as the previous application.

**Comment by brianpattison** [comment]
@RaresSalcudean Hmm... I'm not sure I'll be able to help you much more if the jobs are being reported as enqueued successfully by ActiveJob but they're not actually showing up in the Sidekiq UI or being performed. 

I couldn't tell you if there's anything wrong with your ActiveJob/Sidekiq configuration, so I feel like the next step is to schedule a job in the future manually using ActiveJob and getting that to show up in the Sidekiq UI.

**Comment by brianpattison** [comment]
@RaresSalcudean Even though you're only running the job once per day, there will still always be a minimum of two scheduled jobs for each task.

**Comment by brianpattison** [comment]
@RaresSalcudean I'm not sure what the default setup is for ActiveJob, but make sure you're using the Sidekiq adapter. I'm guessing you're using the default adapter, which is why it's enqueuing successfully but not showing up in Sidekiq.

**Comment by brianpattison** [comment]
@RaresSalcudean Actually, your screenshot shows that you're using the default Async adapter for ActiveJob, so that should be it! 😎

**Comment by RaresSalcudean** [comment]
@brianpattison Thanks I missed that one out! 

Indeed I don't set the following config in the new app: `config.active_job.queue_adapter = :sidekiq`. 

Surprisingly Sidekiq-Cron works without it.

**Comment by brianpattison** [comment]
@RaresSalcudean I'm sure Sidekiq-Cron uses Sidekiq directly and we're using ActiveJob. While we only support the Sidekiq queue adapter, we were hoping we could have the option to support other adapters for Simple Scheduler in the future, which is why we chose to use ActiveJob to enqueue the future jobs.

Glad we could get it figured out!

**Comment by RaresSalcudean** [comment]
@brianpattison Thank you very much for the quick response and help. I will switch back to Simple Scheduler, you guys did a great job with it.
